export enum TipoVeiculoEnum {
    Bicicleta = 1,
    Ciclomoto = 2,
    Motoneta = 3,
    Motociclo = 4,
    Triciclo = 5,
    Automovel = 6,
    MicroOnibus = 7,
    Onibus = 8,
    Bonde = 9,
    Reboque = 10,
    SemiReboque = 11,
    Charrete = 12,
    Camioneta = 13,
    Caminhao = 14,
    Carroca = 15,
    CarroDeMao = 16,
    CaminhaoTrator = 17,
    TratorRodas = 18,
    TratorEsteiras = 19,
    TratorMisto = 20,
    Quadriciclo = 21,
    ChassiPlataforma = 22,
    Caminhonete = 23,
    SideCar = 24,
    Utilitario = 25,
    Inexistente = 99,
    MotorCasa = 26,
    Outros = 0
}

export const tipoVeiculoEnumLabel = new Map<TipoVeiculoEnum, string>([
    [TipoVeiculoEnum.Bicicleta,'Bicicleta'],
    [TipoVeiculoEnum.Ciclomoto,'Ciclomoto'],
    [TipoVeiculoEnum.Motoneta,'Motoneta'],
    [TipoVeiculoEnum.Motociclo,'Motociclo'],
    [TipoVeiculoEnum.Triciclo,'Triciclo'],
    [TipoVeiculoEnum.Automovel,'Automóvel'],
    [TipoVeiculoEnum.MicroOnibus,'Micro-Ônibus'],
    [TipoVeiculoEnum.Onibus,'Ônibus'],
    [TipoVeiculoEnum.Bonde,'Bonde'],
    [TipoVeiculoEnum.Reboque,'Reboque'],
    [TipoVeiculoEnum.SemiReboque,'Semi-Reboque'],
    [TipoVeiculoEnum.Charrete,'Charrete'],
    [TipoVeiculoEnum.Camioneta,'Camioneta'],
    [TipoVeiculoEnum.Caminhao,'Caminhão'],
    [TipoVeiculoEnum.Carroca,'Carroça'],
    [TipoVeiculoEnum.CarroDeMao,'Carro de Mão'],
    [TipoVeiculoEnum.CaminhaoTrator,'Caminhão Trator'],
    [TipoVeiculoEnum.TratorRodas,'Trator Rodas'],
    [TipoVeiculoEnum.TratorEsteiras,'Trator Esteiras'],
    [TipoVeiculoEnum.TratorMisto,'Trator Misto'],
    [TipoVeiculoEnum.Quadriciclo,'Quadriciclo'],
    [TipoVeiculoEnum.ChassiPlataforma,'Chassi Plataforma'],
    [TipoVeiculoEnum.Caminhonete,'Caminhonete'],
    [TipoVeiculoEnum.SideCar,'Side-Car'],
    [TipoVeiculoEnum.Utilitario,'Utilitário'],
    [TipoVeiculoEnum.Inexistente,'Inexistente'],
    [TipoVeiculoEnum.MotorCasa,'Motor Casa'],
    [TipoVeiculoEnum.Outros,'Outros']
]);